server:
  port: 8010


feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true


spring:
  application:
    name: email-service

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://${survey-planet.db.host}:${survey-planet.db.port}/email-log?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR}
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true

  mail:
    host: smtp.163.com
    port: 465
    username: surveyplanet@163.com
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false


mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto


logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"


knife4j:
  enable: true
  openapi:
    title: SurveyPlanet用户信息接口文档
    description: "SurveyPlanet用户信息接口文档"
    email: chenxuanrao06@gmail.com
    concat: rcx
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - org.example.user.controller
