name: Build frontend and deploy to Aliyun
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yaml'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Navigate to frontend directory
      run: cd frontend
    - name: npm install
      run: npm install
      working-directory: ./frontend
    - name: npm run build
      run: npm run build
      working-directory: ./frontend
    - name: Deploy
      uses: cross-the-world/scp-pipeline@master
      env:
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USERNAME }}
        pass: ${{ secrets.SSH_PASSWORD }}
        connect_timeout: 10s
        local: './frontend/dist/*'
        remote: /home/nginx/html
