name: Build backend and deploy to Aliyun

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [gateway, user-service, survey-service]

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置 JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: 构建 ${{ matrix.service }}
        run: |
          cd backend
          mvn clean package -DskipTests -pl ${{ matrix.service }} -am

      - name: 登录 Docker Hub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} ${{ vars.DOCKER_HUB_ADDR }}
        
      - name: 构建 Docker 镜像
        run: |
          cd backend/${{ matrix.service }}
          docker build -t ${{ vars.DOCKER_HUB_ADDR }}/${{ vars.DOCKER_NAMESPACE }}/${{ matrix.service }}:latest .

      - name: 推送 Docker 镜像
        run: docker push ${{ vars.DOCKER_HUB_ADDR }}/${{ vars.DOCKER_NAMESPACE }}/${{ matrix.service }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 连接服务器并部署
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/project
            docker compose down
            docker pull ${{ vars.DOCKER_HUB_ADDR }}/${{ vars.DOCKER_NAMESPACE }}/gateway:latest
            docker pull ${{ vars.DOCKER_HUB_ADDR }}/${{ vars.DOCKER_NAMESPACE }}/user-service:latest
            docker pull ${{ vars.DOCKER_HUB_ADDR }}/${{ vars.DOCKER_NAMESPACE }}/survey-service:latest
            docker compose up -d
